<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="CopyPvRecorderNativeLibs" AfterTargets="Build">
		<ItemGroup>
			<_PvNativeLibs Include="$(MSBuildThisFileDirectory)lib\**\*" />
		</ItemGroup>
		<Copy
			SourceFiles="@(_PvNativeLibs)"
			DestinationFiles="@(_PvNativeLibs->'$(OutDir)lib\%(RecursiveDir)%(Filename)%(Extension)')"
			SkipUnchangedFiles="true"
		/>
	</Target>
</Project>